### PR TITLE
Add support to more node.JS versions

### PR DESCRIPTION
**Pull request by simonepri**
This should close:
https://github.com/keymetrics/pm2-docker-alpine/issues/10
More info here:
https://github.com/keymetrics/pm2-docker-alpine/pull/11

### CODE REVIEW

**Comment by simonepri** [comment]
@Unitech Let us know when you have pulled the image on Docker Registry
Thanks

**Comment by Unitech** [comment]
Thanks for this PR. Do you have a Docker hub username? I will invite you as a collaborator

**Comment by Unitech** [comment]
Added ;)

**Comment by simonepri** [comment]
https://hub.docker.com/u/simonepri/

**Comment by simonepri** [comment]
Yes sure:
https://hub.docker.com/u/simonepri/

**Comment by Unitech** [comment]
Alright everything seems to work now https://hub.docker.com/r/keymetrics/pm2-docker-alpine/tags/

Thanks for help!

**Comment by simonepri** [comment]
Amazing. 🦄 🎉 🎈 
Thank you for your availability.

**Pull request merged**
