### PR TITLE
New README file

### PR DESCRIPTION
**Pull request by simonepri**
The preview can be seen here:
https://github.com/simonepri/pm2-docker-alpine/blob/95d5001f9b7603d94972273eae4be01b68b6fe04/README.md

### CODE REVIEW

**Comment by simonepri** [comment]
@Unitech can you review it looking for some grammar errors? Thank you.

**Comment by vmarchaud** [comment]
Looks good to me :)

**Comment by simonepri** [comment]
Do I go with the marge?
Is there anything else we can add?

**Comment by vmarchaud** [comment]
@simonepri Lets go

**Pull request merged**
