### PR TITLE
Install pm2-auto-pull when building the image

### PR DESCRIPTION
**Pull request by Xoib**
Regarding issue #7, is it what you are looking for?

### CODE REVIEW

**Comment by simonepri** [comment]
@Unitech Could that be marged?

**Comment by Unitech** [comment]
That module should not me be installed by default, we can document it in the README.md though

**Comment by simonepri** [comment]
Ok, so what about the #7 ?

**Comment by simonepri** [comment]
@Unitech 
It seems to be already documented into the README.
I think we can close it

**Pull request closed without merging**
